const baseLevels = [
  { segments: 20, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 16, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 12, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 8, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 4, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 3, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0, splitSmoothness: 1 },
]

const makePreset = (
  name,
  leafStyle,
  leafArrangement,
  leafColor,
  barkColor,
  barkTint,
  fiberIntensity,
  crackDepth,
  mossAmount,
  blendBias,
  roughnessVar,
  twigDensity,
  twigLength,
  twigPhototropism,
  twigGravity,
  leaderDefaults,
) => ({
  name,
  leafStyle,
  leafArrangement,
  seed: 108,
  height: 40,
  radius: 1,
  taper: 0.02,
  recursion: 3,
  leaderCount: leaderDefaults.leaderCount,
  leaderStartMin: leaderDefaults.leaderStartMin,
  leaderStartMax: leaderDefaults.leaderStartMax,
  leaderSplitChance: leaderDefaults.leaderSplitChance,
  leaderUpwardBias: leaderDefaults.leaderUpwardBias,
  leaderThicknessRetention: leaderDefaults.leaderThicknessRetention,
  leaderLengthBias: leaderDefaults.leaderLengthBias,
  leaderDominance: leaderDefaults.leaderDominance,
  leaderInheritance: leaderDefaults.leaderInheritance,
  leafCount: 5000,
  leafSize: 0.35,
  tropismUp: 1,
  gravity: 1,
  leafColor,
  barkColor,
  barkTint,
  fiberIntensity,
  crackDepth,
  mossAmount,
  blendBias,
  roughnessVar,
  twigDensity,
  twigLength,
  twigPhototropism,
  twigGravity,
  levels: JSON.parse(JSON.stringify(baseLevels)),
  camPitch: 15,
  camYaw: 45,
  camDist: 100,
  orbitMode: 'specimen-locked',
  camTargetX: 0,
  camTargetY: 21.25,
  camTargetZ: 0,
})

export const SPECIES_PRESETS = {
  Pine: makePreset('Pine', 'needle', 'alternate', '#1a3311', '#4a3320', '#6b4830', 0.8, 0.8, 0.1, 0.8, 0.7, 5, 1.2, 1.5, 0.1, {
    leaderCount: 1,
    leaderStartMin: 0.12,
    leaderStartMax: 0.38,
    leaderSplitChance: 0.12,
    leaderUpwardBias: 1.5,
    leaderThicknessRetention: 0.95,
    leaderLengthBias: 1.1,
    leaderDominance: 1.1,
    leaderInheritance: 0.9,
  }),
  Oak: makePreset('Oak', 'broadleaf', 'alternate', '#2d5a27', '#3a2e24', '#5c5248', 0.5, 0.9, 0.3, 0.4, 0.8, 3, 1.5, 0.8, 0.2, {
    leaderCount: 2,
    leaderStartMin: 0.24,
    leaderStartMax: 0.58,
    leaderSplitChance: 0.48,
    leaderUpwardBias: 1.0,
    leaderThicknessRetention: 0.82,
    leaderLengthBias: 0.92,
    leaderDominance: 0.88,
    leaderInheritance: 0.72,
  }),
  Willow: makePreset('Willow', 'hanging', 'alternate', '#8ca36f', '#4b4d3f', '#6b6e5b', 0.9, 0.3, 0.5, 0.3, 0.5, 2, 4, -0.5, 1.8, {
    leaderCount: 1,
    leaderStartMin: 0.18,
    leaderStartMax: 0.44,
    leaderSplitChance: 0.22,
    leaderUpwardBias: 0.78,
    leaderThicknessRetention: 0.68,
    leaderLengthBias: 0.84,
    leaderDominance: 0.58,
    leaderInheritance: 0.42,
  }),
  Birch: makePreset('Birch', 'broadleaf', 'alternate', '#a9c95d', '#d6d6d6', '#333333', 0.2, 0.2, 0.05, 0.9, 0.4, 4, 1, 0.6, 0.1, {
    leaderCount: 2,
    leaderStartMin: 0.2,
    leaderStartMax: 0.5,
    leaderSplitChance: 0.34,
    leaderUpwardBias: 1.22,
    leaderThicknessRetention: 0.72,
    leaderLengthBias: 0.9,
    leaderDominance: 0.76,
    leaderInheritance: 0.66,
  }),
  Cypress: makePreset('Cypress', 'shell', 'opposite', '#1e3d14', '#5c4b3f', '#786558', 0.7, 0.6, 0.2, 0.6, 0.6, 6, 0.5, 0.2, 0.05, {
    leaderCount: 3,
    leaderStartMin: 0.14,
    leaderStartMax: 0.34,
    leaderSplitChance: 0.55,
    leaderUpwardBias: 1.65,
    leaderThicknessRetention: 1.02,
    leaderLengthBias: 1.05,
    leaderDominance: 1.18,
    leaderInheritance: 0.94,
  }),
}

export const clonePresetParams = (presetName) => JSON.parse(JSON.stringify(SPECIES_PRESETS[presetName] ?? SPECIES_PRESETS.Pine))
