const baseLevels = [
  { segments: 20, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 16, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 12, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 8, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 4, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0.3, splitSmoothness: 1 },
  { segments: 3, curve: 0.5, branchCount: 7, branchAngle: 1, lengthScale: 0.75, radiusScale: 0.7, apicalControl: 0.5, splitChance: 0, splitSmoothness: 1 },
]

const createRecipe = ({
  name,
  family,
  leafStyle,
  leafArrangement,
  leafColor,
  barkColor,
  barkTint,
  fiberIntensity,
  crackDepth,
  mossAmount,
  blendBias,
  roughnessVar,
  twigDensity,
  twigLength,
  twigPhototropism,
  twigGravity,
  terrainDefaults = {
    terrainCenterX: 210,
    terrainCenterZ: -130,
    terrainInnerRadius: 260,
    terrainSmallRidgeRadius: 560,
    terrainLargeRidgeRadius: 980,
    terrainOuterRimRadius: 1440,
    terrainInnerDepth: -26,
    terrainSmallRidgeHeight: 12,
    terrainLargeRidgeHeight: 24,
    terrainOuterRimHeight: 42,
    terrainNoiseAmplitude: 8.5,
    terrainNoiseFrequency: 0.0018,
    terrainMicroNoiseAmplitude: 2.6,
    terrainMicroNoiseFrequency: 0.009,
    terrainSlopeSharpening: 1.1,
    terrainBasinFlattening: 0.55,
  },
  trunkDefaults = {
    trunkUprightStrength: 0.7,
    trunkNoiseDamping: 0.55,
    trunkLeanLimit: 0.22,
  },
  leaderDefaults,
  awarenessDefaults,
  terrainProfile = 'greenhouse-concentric-bowl-v1',
}) => ({
  id: `recipe:${name.toLowerCase()}`,
  name,
  family,
  mode: family === 'conifer' ? 'conifer' : 'broadleaf',
  strategyKeys: {
    growth: family,
    leafPlacement: leafStyle,
    twig: 'default',
    terrain: terrainProfile,
    material: 'botanical-glasshouse-v1',
  },
  descriptors: {
    terrain: {
      profile: terrainProfile,
      size: 2800,
      resolution: 180,
      seed: 42,
      ...terrainDefaults,
    },
    materials: {
      bark: {
        barkColor,
        barkTint,
        fiberIntensity,
        crackDepth,
        mossAmount,
        blendBias,
        roughnessVar,
      },
      foliage: {
        leafColor,
        leafStyle,
        leafArrangement,
      },
    },
    camera: {
      camPitch: 15,
      camYaw: 45,
      camDist: 100,
      orbitMode: 'specimen-locked',
    },
  },
  defaults: {
    name,
    leafStyle,
    leafArrangement,
    seed: 108,
    simulationYears: 20,
    ticksPerYear: 12,
    height: 40,
    radius: 1,
    taper: 0.02,
    recursion: 3,
    ...trunkDefaults,
    ...leaderDefaults,
    ...awarenessDefaults,
    leafCount: 5000,
    leafSize: 0.35,
    tropismUp: 1,
    gravity: 1,
    leafColor,
    barkColor,
    barkTint,
    fiberIntensity,
    crackDepth,
    mossAmount,
    blendBias,
    roughnessVar,
    twigDensity,
    twigLength,
    twigPhototropism,
    twigGravity,
    ...terrainDefaults,
    levels: structuredClone(baseLevels),
    camPitch: 15,
    camYaw: 45,
    camDist: 100,
    orbitMode: 'specimen-locked',
    camTargetX: 0,
    camTargetY: 21.25,
    camTargetZ: 0,
  },
})

export const SPECIES_RECIPES = {
  Pine: createRecipe({
    name: 'Pine',
    family: 'conifer',
    leafStyle: 'needle',
    leafArrangement: 'alternate',
    leafColor: '#1a3311',
    barkColor: '#4a3320',
    barkTint: '#6b4830',
    fiberIntensity: 0.8,
    crackDepth: 0.8,
    mossAmount: 0.1,
    blendBias: 0.8,
    roughnessVar: 0.7,
    twigDensity: 5,
    twigLength: 1.2,
    twigPhototropism: 1.5,
    twigGravity: 0.1,
    terrainDefaults: {
      terrainCenterX: 190,
      terrainCenterZ: -110,
      terrainInnerRadius: 230,
      terrainSmallRidgeRadius: 520,
      terrainLargeRidgeRadius: 940,
      terrainOuterRimRadius: 1390,
      terrainInnerDepth: -24,
      terrainSmallRidgeHeight: 14,
      terrainLargeRidgeHeight: 22,
      terrainOuterRimHeight: 44,
      terrainNoiseAmplitude: 7.5,
      terrainNoiseFrequency: 0.0016,
      terrainMicroNoiseAmplitude: 2.2,
      terrainMicroNoiseFrequency: 0.008,
      terrainSlopeSharpening: 1.08,
      terrainBasinFlattening: 0.6,
    },
    trunkDefaults: {
      trunkUprightStrength: 0.92,
      trunkNoiseDamping: 0.9,
      trunkLeanLimit: 0.12,
    },
    leaderDefaults: {
      leaderCount: 1,
      leaderStartMin: 0.12,
      leaderStartMax: 0.38,
      leaderSplitChance: 0.12,
      leaderUpwardBias: 1.5,
      leaderThicknessRetention: 0.95,
      leaderLengthBias: 1.1,
      leaderDominance: 1.1,
      leaderInheritance: 0.9,
    },
    awarenessDefaults: {
      branchAwarenessRadius: 5.8,
      branchExclusionRadius: 0.8,
      branchRepulsionStrength: 0.95,
      branchCrowdingPenalty: 0.2,
      branchCrowdedDeathChance: 0.12,
      branchOutwardBias: 0.65,
      leaderAwarenessRadius: 12,
      leaderProjectionLength: 1.7,
      leaderCorridorWidth: 1.5,
      leaderRepulsionStrength: 1.2,
      leaderParallelPenalty: 0.9,
      leaderRedundancyPenalty: 0.8,
      leaderYieldThreshold: 0.46,
      primaryLeaderProtection: 0.88,
      leaderGraceDistance: 4.5,
      crownZoneSeparationStrength: 0.95,
    },
  }),
  Oak: createRecipe({
    name: 'Oak',
    family: 'broadleaf',
    leafStyle: 'broadleaf',
    leafArrangement: 'alternate',
    leafColor: '#2d5a27',
    barkColor: '#3a2e24',
    barkTint: '#5c5248',
    fiberIntensity: 0.5,
    crackDepth: 0.9,
    mossAmount: 0.3,
    blendBias: 0.4,
    roughnessVar: 0.8,
    twigDensity: 3,
    twigLength: 1.5,
    twigPhototropism: 0.8,
    twigGravity: 0.2,
    terrainDefaults: {
      terrainCenterX: 220,
      terrainCenterZ: -140,
      terrainInnerRadius: 300,
      terrainSmallRidgeRadius: 620,
      terrainLargeRidgeRadius: 1080,
      terrainOuterRimRadius: 1510,
      terrainInnerDepth: -28,
      terrainSmallRidgeHeight: 10,
      terrainLargeRidgeHeight: 26,
      terrainOuterRimHeight: 40,
      terrainNoiseAmplitude: 8.5,
      terrainNoiseFrequency: 0.0019,
      terrainMicroNoiseAmplitude: 2.8,
      terrainMicroNoiseFrequency: 0.0095,
      terrainSlopeSharpening: 1.14,
      terrainBasinFlattening: 0.5,
    },
    trunkDefaults: {
      trunkUprightStrength: 0.66,
      trunkNoiseDamping: 0.62,
      trunkLeanLimit: 0.22,
    },
    leaderDefaults: {
      leaderCount: 2,
      leaderStartMin: 0.24,
      leaderStartMax: 0.58,
      leaderSplitChance: 0.48,
      leaderUpwardBias: 1,
      leaderThicknessRetention: 0.82,
      leaderLengthBias: 0.92,
      leaderDominance: 0.88,
      leaderInheritance: 0.72,
    },
    awarenessDefaults: {
      branchAwarenessRadius: 7.2,
      branchExclusionRadius: 1.25,
      branchRepulsionStrength: 0.88,
      branchCrowdingPenalty: 0.26,
      branchCrowdedDeathChance: 0.16,
      branchOutwardBias: 0.42,
      leaderAwarenessRadius: 14.5,
      leaderProjectionLength: 1.4,
      leaderCorridorWidth: 1.9,
      leaderRepulsionStrength: 1.1,
      leaderParallelPenalty: 0.78,
      leaderRedundancyPenalty: 1.02,
      leaderYieldThreshold: 0.4,
      primaryLeaderProtection: 0.62,
      leaderGraceDistance: 5.8,
      crownZoneSeparationStrength: 0.8,
    },
  }),
  Willow: createRecipe({
    name: 'Willow',
    family: 'hanging',
    leafStyle: 'hanging',
    leafArrangement: 'alternate',
    leafColor: '#8ca36f',
    barkColor: '#4b4d3f',
    barkTint: '#6b6e5b',
    fiberIntensity: 0.9,
    crackDepth: 0.3,
    mossAmount: 0.5,
    blendBias: 0.3,
    roughnessVar: 0.5,
    twigDensity: 2,
    twigLength: 4,
    twigPhototropism: -0.5,
    twigGravity: 1.8,
    trunkDefaults: {
      trunkUprightStrength: 0.48,
      trunkNoiseDamping: 0.34,
      trunkLeanLimit: 0.28,
    },
    leaderDefaults: {
      leaderCount: 1,
      leaderStartMin: 0.18,
      leaderStartMax: 0.44,
      leaderSplitChance: 0.22,
      leaderUpwardBias: 0.78,
      leaderThicknessRetention: 0.68,
      leaderLengthBias: 0.84,
      leaderDominance: 0.58,
      leaderInheritance: 0.42,
    },
    awarenessDefaults: {
      branchAwarenessRadius: 6.5,
      branchExclusionRadius: 1,
      branchRepulsionStrength: 0.72,
      branchCrowdingPenalty: 0.18,
      branchCrowdedDeathChance: 0.1,
      branchOutwardBias: 0.32,
      leaderAwarenessRadius: 11,
      leaderProjectionLength: 1.25,
      leaderCorridorWidth: 1.7,
      leaderRepulsionStrength: 0.82,
      leaderParallelPenalty: 0.56,
      leaderRedundancyPenalty: 0.72,
      leaderYieldThreshold: 0.32,
      primaryLeaderProtection: 0.4,
      leaderGraceDistance: 4,
      crownZoneSeparationStrength: 0.62,
    },
  }),
  Birch: createRecipe({
    name: 'Birch',
    family: 'broadleaf',
    leafStyle: 'broadleaf',
    leafArrangement: 'alternate',
    leafColor: '#a9c95d',
    barkColor: '#d6d6d6',
    barkTint: '#333333',
    fiberIntensity: 0.2,
    crackDepth: 0.2,
    mossAmount: 0.05,
    blendBias: 0.9,
    roughnessVar: 0.4,
    twigDensity: 4,
    twigLength: 1,
    twigPhototropism: 0.6,
    twigGravity: 0.1,
    terrainDefaults: {
      terrainCenterX: 180,
      terrainCenterZ: -155,
      terrainInnerRadius: 210,
      terrainSmallRidgeRadius: 500,
      terrainLargeRidgeRadius: 900,
      terrainOuterRimRadius: 1360,
      terrainInnerDepth: -22,
      terrainSmallRidgeHeight: 13,
      terrainLargeRidgeHeight: 20,
      terrainOuterRimHeight: 38,
      terrainNoiseAmplitude: 6.8,
      terrainNoiseFrequency: 0.0015,
      terrainMicroNoiseAmplitude: 2,
      terrainMicroNoiseFrequency: 0.007,
      terrainSlopeSharpening: 1.05,
      terrainBasinFlattening: 0.62,
    },
    trunkDefaults: {
      trunkUprightStrength: 0.76,
      trunkNoiseDamping: 0.68,
      trunkLeanLimit: 0.18,
    },
    leaderDefaults: {
      leaderCount: 2,
      leaderStartMin: 0.2,
      leaderStartMax: 0.5,
      leaderSplitChance: 0.34,
      leaderUpwardBias: 1.22,
      leaderThicknessRetention: 0.72,
      leaderLengthBias: 0.9,
      leaderDominance: 0.76,
      leaderInheritance: 0.66,
    },
    awarenessDefaults: {
      branchAwarenessRadius: 6,
      branchExclusionRadius: 0.9,
      branchRepulsionStrength: 1,
      branchCrowdingPenalty: 0.24,
      branchCrowdedDeathChance: 0.14,
      branchOutwardBias: 0.58,
      leaderAwarenessRadius: 13,
      leaderProjectionLength: 1.55,
      leaderCorridorWidth: 1.4,
      leaderRepulsionStrength: 1.18,
      leaderParallelPenalty: 0.86,
      leaderRedundancyPenalty: 0.88,
      leaderYieldThreshold: 0.42,
      primaryLeaderProtection: 0.7,
      leaderGraceDistance: 4.8,
      crownZoneSeparationStrength: 0.9,
    },
  }),
  Cypress: createRecipe({
    name: 'Cypress',
    family: 'shell',
    leafStyle: 'shell',
    leafArrangement: 'opposite',
    leafColor: '#1e3d14',
    barkColor: '#5c4b3f',
    barkTint: '#786558',
    fiberIntensity: 0.7,
    crackDepth: 0.6,
    mossAmount: 0.2,
    blendBias: 0.6,
    roughnessVar: 0.6,
    twigDensity: 6,
    twigLength: 0.5,
    twigPhototropism: 0.2,
    twigGravity: 0.05,
    terrainDefaults: {
      terrainCenterX: 205,
      terrainCenterZ: -125,
      terrainInnerRadius: 250,
      terrainSmallRidgeRadius: 540,
      terrainLargeRidgeRadius: 980,
      terrainOuterRimRadius: 1420,
      terrainInnerDepth: -25,
      terrainSmallRidgeHeight: 11,
      terrainLargeRidgeHeight: 23,
      terrainOuterRimHeight: 43,
      terrainNoiseAmplitude: 7.8,
      terrainNoiseFrequency: 0.0017,
      terrainMicroNoiseAmplitude: 2.4,
      terrainMicroNoiseFrequency: 0.0085,
      terrainSlopeSharpening: 1.12,
      terrainBasinFlattening: 0.58,
    },
    trunkDefaults: {
      trunkUprightStrength: 0.95,
      trunkNoiseDamping: 0.92,
      trunkLeanLimit: 0.1,
    },
    leaderDefaults: {
      leaderCount: 3,
      leaderStartMin: 0.14,
      leaderStartMax: 0.34,
      leaderSplitChance: 0.55,
      leaderUpwardBias: 1.65,
      leaderThicknessRetention: 1.02,
      leaderLengthBias: 1.05,
      leaderDominance: 1.18,
      leaderInheritance: 0.94,
    },
    awarenessDefaults: {
      branchAwarenessRadius: 4.8,
      branchExclusionRadius: 0.72,
      branchRepulsionStrength: 1.08,
      branchCrowdingPenalty: 0.16,
      branchCrowdedDeathChance: 0.08,
      branchOutwardBias: 0.72,
      leaderAwarenessRadius: 15,
      leaderProjectionLength: 1.85,
      leaderCorridorWidth: 1.2,
      leaderRepulsionStrength: 1.28,
      leaderParallelPenalty: 1.02,
      leaderRedundancyPenalty: 0.84,
      leaderYieldThreshold: 0.5,
      primaryLeaderProtection: 0.9,
      leaderGraceDistance: 5.2,
      crownZoneSeparationStrength: 1.02,
    },
  }),
}

export const buildParamsFromRecipe = (recipe) => structuredClone(recipe.defaults)

export const cloneRecipeByName = (name) => structuredClone(SPECIES_RECIPES[name] ?? SPECIES_RECIPES.Pine)
